### ISSUE TITLE
incorrect dnsmasq conf-dir path

### ISSUE THREAD

**Issue by st7105** [stangri/pbr#11]
On new version dnsmasq configuration path /var/etc/dnsmasq.conf.cfg01411c

`conf-dir=/tmp/dnsmasq.cfg01411c.d`

before commit https://github.com/openwrt/openwrt/commit/3407269ba593aec49583d036ff1f8745bde330dc

`conf-dir=/tmp/dnsmasq.d`

**Comment by st7105** [comment]
Problem resolved.

**Comment by st7105** [comment]
The problem is relevant again on version 1.1.7-47

**Comment by stangri** [comment]
The problem will be relevant until the dnsmasq init code is fixed as per my PR submitted in openwrt/openwrt repo. It's not just the pbr package which is affected, it's other packages as well, so the dnsmasq needs to be fixed.

If you need to use the snapshots, fix the dnsmasq init script on your install.
